config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    get '/login_as/:user_id', to: 'development/sessions#login_as'
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  namespace :admin do
    namespace :login do
      resource :identifier, only: %i[show create]
      resource :password, only: %i[show create]
    end
    resource :logout, only: %i[destroy]
    resource :dashboard, only: %i[show]
    resources :users
    resources :invitations, param: :uuid, only: %i[index new create destroy] do
      resource :register, only: %i[show create]
    end
    resource :site, only: %i[edit update] do
      resources :attachments, controller: 'site/attachments', only: %i[destroy]
    end
    resources :categories, only: %i[index create edit update destroy]
    resources :tags, only: %i[index create edit update destroy]
    resources :authors, only: %i[index create edit update destroy]
    resources :articles, param: :uuid, only: %i[index new create edit update destroy] do
      resource :preview, controller: 'articles/previews', only: %i[show]
      resource :publish, controller: 'articles/publishes', only: %i[update]
      resources :article_blocks, controller: 'articles/article_blocks', only: %i[index show create edit update destroy] do
        patch :swap_level
      end
    end
  end

  get '/admin' => redirect('/admin/login/identifier')

  get '/tags/:tag_slug', as: :tag, to: 'articles#index'
  get '/authors/:author_slug', as: :author, to: 'articles#index'
  get '/:category_slug', as: :category, to: 'articles#index'
  get '/:category_slug/:article_slug', as: :article, to: 'articles#show'

  root 'articles#index'
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id           :bigint           not null, primary key
#  category_id  :bigint
#  author_id    :bigint
#  uuid         :string(255)
#  slug         :string(255)
#  title        :string(255)
#  description  :text(65535)
#  body         :text(65535)
#  state        :integer          default("draft"), not null
#  published_at :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  deleted_at   :datetime
#
# Indexes
#
#  index_articles_on_author_id     (author_id)
#  index_articles_on_category_id   (category_id)
#  index_articles_on_deleted_at    (deleted_at)
#  index_articles_on_published_at  (published_at)
#  index_articles_on_slug          (slug)
#  index_articles_on_uuid          (uuid)
#

class Article < ApplicationRecord
  belongs_to :category
  belongs_to :author

  has_many :article_tags
  has_many :tags, through: :article_tags
  has_many :article_blocks, -> { order(:level) }, inverse_of: :article
  has_many :sentences, through: :article_blocks, source: :blockable, source_type: 'Sentence'
  has_many :media, through: :article_blocks, source: :blockable, source_type: 'Medium'
  has_many :embeds, through: :article_blocks, source: :blockable, source_type: 'Embed'

  has_one_attached :eye_catch

  enum state: { draft: 0, published: 1, publish_wait: 2 }
  enum eyecatch_align: { left: 0, center: 1, right: 2 }

  validates :slug, slug_format: true, uniqueness: true, length: { maximum: 255 }, allow_blank: true
  validates :title, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :description, length: { maximum: 1000 }, allow_blank: true
  validates :state, presence: true
  validates :eye_catch, attachment: { purge: true, content_type: %r{\Aimage/(png|jpeg)\Z}, maximum: 10_485_760 }
  validates :eyecatch_width, numericality: { less_than_or_equal_to: 700, greater_than_or_equal_to: 100 }, allow_blank: true

  with_options if: :published? do
    validates :slug, slug_format: true, presence: true, length: { maximum: 255 }
    validates :published_at, presence: true
    validates :category_id, presence: true
  end

  delegate :name, to: :category, prefix: true, allow_nil: true
  delegate :slug, to: :category, prefix: true, allow_nil: true
  delegate :name, to: :author, prefix: true, allow_nil: true

  before_create -> { self.uuid = SecureRandom.uuid }

  scope :viewable, -> { published.where('published_at < ?', Time.current) }
  scope :new_arrivals, -> { viewable.order(published_at: :desc) }
  scope :by_category, ->(category_id) { where(category_id: category_id) }
  scope :title_contain, ->(word) { where('title LIKE ?', "%#{word}%") }
  scope :by_author, ->(author_id) { where(author_id: author_id) }
  scope :by_tag, ->(tag_id) { joins(:article_tags).where(article_tags: { tag_id: tag_id }) }
  scope :body_contain, ->(body) { joins(:sentences).merge(where('sentences.body LIKE ?', "%#{body}%")) }
  scope :past_published, -> { where('published_at <= ?', Time.current) }
  scope :published_at_yesterday, -> { published.where(published_at: 1.day.ago.all_day) }

  def build_body(controller)
    result = ''

    article_blocks.each do |article_block|
      result << if article_block.sentence?
                  sentence = article_block.blockable
                  sentence.body ||= ''
                elsif article_block.medium?
                  medium = ActiveDecorator::Decorator.instance.decorate(article_block.blockable)
                  controller.render_to_string("shared/_media_#{medium.media_type}", locals: { medium: medium }, layout: false)
                elsif article_block.embed?
                  embed = ActiveDecorator::Decorator.instance.decorate(article_block.blockable)
                  controller.render_to_string("shared/_embed_#{embed.embed_type}", locals: { embed: embed }, layout: false)
                end
    end

    result
  end

  def next_article
    @next_article ||= Article.viewable.order(published_at: :asc).find_by('published_at > ?', published_at)
  end

  def prev_article
    @prev_article ||= Article.viewable.order(published_at: :desc).find_by('published_at < ?', published_at)
  end

  def publishable?
    Time.current >= published_at
  end

  def message_on_published
    if published?
      '公開しました'
    elsif publish_wait?
      '公開待ちにしました'
    end
  end

  def adjust_state
    return if draft?

    self.state = if publishable?
                   :published
                 else
                   :publish_wait
                 end
  end
end

app/controllers/admin/articles/article_blocks_controller.rb
class Admin::Articles::ArticleBlocksController < ApplicationController
  layout false

  before_action :set_article
  before_action :set_article_block, only: %i[show edit update destroy]

  def index
    @article_blocks = @article.article_blocks.preload(:blockable)
  end

  def show; end

  def create
    ArticleBlock.transaction do
      @article_block = @article.article_blocks.new(article_block_params)

      if @article_block.invalid?(:insert)
        return head :bad_request
      end

      blockable_type = params.dig(:article_block, :blockable_type)

      if blockable_type.blank? || !ArticleBlock.valid_blockable_type?(blockable_type)
        return head :bad_request
      end

      @article_block.create_blockable!(blockable_type)
      @article_block.insert_and_save!
    end

    head :ok
  end

  def edit; end

  def update
    if @article_block.blockable.update(blockable_params)
      if @article_block.medium?
        redirect_to edit_admin_article_path(@article.uuid)
      else
        head :ok
      end
    else
      render action: :edit, status: :bad_request
    end
  end

  def destroy
    @article_block.destroy!
    head :ok
  end

  def swap_level
    article_block1 = @article.article_blocks.find(params[:article_block_id])

    level = article_block_params[:level]

    if level.blank? || level.to_i.negative? || level.to_i >= @article.article_blocks.count
      return head :bad_request
    end

    article_block2 = @article.article_blocks.find_by!(level: level)

    if article_block1 == article_block2
      return head :bad_request
    end

    article_block2.level = article_block1.level
    article_block1.level = level

    ArticleBlock.transaction do
      article_block1.save!(context: :swap_level)
      article_block2.save!(context: :swap_level)
    end

    head :ok
  end

  private

  def article_block_params
    params.require(:article_block).permit(:level)
  end

  def blockable_params
    if params.key?(:sentence)
      sentence_params
    elsif params.key?(:medium)
      medium_params
    elsif params.key?(:embed)
      embed_params
    else
      raise ActionController::ParameterMissing, :blockable
    end
  end

  def sentence_params
    params.require(:sentence).permit(:body)
  end

  def medium_params
    params.require(:medium).permit(:medium_type, :attachment)
  end

  def embed_params
    params.require(:embed).permit(:embed_type, :identifier)
  end

  def set_article
    @article = Article.find_by!(uuid: params[:article_uuid])
  end

  def set_article_block
    @article_block = @article.article_blocks.find(params[:id])
  end
end

app/controllers/admin/articles/previews_controller.rb
class Admin::Articles::PreviewsController < ApplicationController
  skip_before_action :require_login

  before_action :preview!

  def show
    @article = Article.find_by!(uuid: params[:article_uuid])
    @article.body = @article.build_body(self)
  end
end

app/controllers/admin/articles/publishes_controller.rb
class Admin::Articles::PublishesController < ApplicationController
  layout 'admin'

  before_action :set_article

  def update
    @article.published_at = Time.current unless @article.published_at?
    @article.state = @article.publishable? ? :published : :publish_wait

    if @article.valid?
      Article.transaction do
        @article.body = @article.build_body(self)
        @article.save!
      end

      flash[:notice] = @article.message_on_published
      redirect_to edit_admin_article_path(@article.uuid)
    else
      flash.now[:alert] = 'エラーがあります。確認してください。'

      @article.state = @article.state_was if @article.state_changed?
      render 'admin/articles/edit'
    end
  end

  private

  def set_article
    @article = Article.find_by!(uuid: params[:article_uuid])
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  layout 'admin'

  before_action :set_article, only: %i[edit update destroy]

  def index
    authorize(Article)

    @search_articles_form = SearchArticlesForm.new(search_params)
    @articles = @search_articles_form.search.order(id: :desc).page(params[:page]).per(25)
  end

  def new
    @article = Article.new
  end

  def create
    authorize(Article)

    @article = Article.new(article_params)
    @article.state = :draft

    if @article.save
      redirect_to edit_admin_article_path(@article.uuid)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize(@article)
  end

  def update
    authorize(@article)

    @article.assign_attributes(article_params)
    @article.adjust_state
    if @article.save
      flash[:notice] = '更新しました'
      redirect_to edit_admin_article_path(@article.uuid)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize(@article)

    @article.destroy

    redirect_to admin_articles_path
  end

  private

  def article_params
    params.require(:article).permit(
      :title, :description, :slug, :state, :published_at, :eye_catch, :eyecatch_width, :eyecatch_align, :category_id, :author_id, tag_ids: []
    )
  end

  def search_params
    params[:q]&.permit(:title, :body, :category_id, :author_id, :tag_id)
  end

  def set_article
    @article = Article.find_by!(uuid: params[:uuid])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :require_login
  def index
    @articles = if params[:tag_slug].present?
                  set_tag
                  @tag.articles
                elsif params[:author_slug].present?
                  set_author
                  @author.articles
                elsif params[:category_slug].present?
                  set_category
                  @category.articles
                else
                  hide_new_arrivals!
                  hide_pagination!
                  Article.all
                end

    @articles = @articles.new_arrivals.page(params[:page]).per(20)
  end

  def show
    @category = Category.find_by!(slug: params[:category_slug])
    @article = @category.articles.find_by!(slug: params[:article_slug])
  end

  private

  def set_tag
    @tag = Tag.find_by!(slug: params[:tag_slug])
    @title = @tag.name
  end

  def set_author
    @author = Author.find_by!(slug: params[:author_slug])
    @title = @author.name
  end

  def set_category
    @category = Category.find_by!(slug: params[:category_slug])
    @title = @category.name
  end
end

app/views/admin/articles/edit.html.slim
= content_for 'scripts' do
  = javascript_include_tag 'edit_article'

= content_for 'content-header' do
  = @article.title

- breadcrumb :edit_admin_article, @article

.row
  .col-md-8
    = content_tag 'div', nil, class: 'js-article-block-forms', data: { 'article-uuid' => @article.uuid } do
      .text-center
        i.fa.fa-spinner.fa-pulse.fa-3x.fa-fw

  .col-md-4
    .box.box-solid.box-info
      .box-header
        h3.box-title 情報

      = simple_form_for @article, local: true, url: admin_article_path(@article.uuid) do |f|
        = render 'layouts/error_messages', model: f.object
        .box-body
          - if @article.draft?
            .form-group
              label.control-label = Article.human_attribute_name(:state)
              .form-control = @article.state_i18n
          - else
            = f.input :state, collect: Article.states_i18n.invert, include_blank: false

          = f.input :published_at, as: :date_time_picker
          = f.input :title
          = f.input :slug
          = f.input :eye_catch, as: :file
          - if @article.eye_catch.attached?
            = image_tag @article.eye_catch_url(:thumb), class: 'img-thumbnail'
            br
            br
          = f.input :eyecatch_width, placeholder: '100'
          = f.input_field :eyecatch_align, as: :radio_buttons
          = f.input :description, input_html: { class: 'js-autosize' }
          = f.input :author_id, as: :select2, collection: Author.pluck(:name, :id)
          = f.input :category_id, as: :select2, collection: Category.pluck(:name, :id)
          = f.input :tag_ids, as: :select2, collection: Tag.pluck(:name, :id), include_blank: false, input_html: { multiple: true }

        .box-footer
          = f.button :submit, class: %w[btn btn-primary]

    .box.box-solid.box-info
      .box-header
        h3.box-title 公開
      .box-body
        = link_to admin_article_preview_path(@article.uuid), class: %w[btn btn-default btn-block btn-flat], target: '_blank' do
          i.fa.fa-eye
          '
          | プレビュー
        - if @article.published?
          = link_to article_path(@article.category_slug, @article.slug), class: %w[btn btn-default btn-block btn-flat], target: '_blank' do
            i.fa.fa-globe
            '
            | 公開ページ
      .box-footer
        = link_to admin_article_publish_path(@article.uuid), class: %w[btn btn-success btn-block btn-flat], method: :patch do
          i.fa.fa-send
          '
          | 公開する

app/views/admin/articles/index.html.slim
= content_for 'content-header' do
  | 記事

- breadcrumb :admin_articles

.box.box-primary
  .box-header
    h3.box-title 記事一覧
    .box-tools
      .ul.list-inline
        li
          = form_with model: @search_articles_form, scope: :q, url: admin_articles_path, method: :get, html: { class: 'form-inline' } do |f|
            => f.select :category_id, Category.pluck(:name, :id) , { include_blank: "カテゴリ" }, class: 'form-control'
            => f.select :author_id, Author.pluck(:name, :id) , { include_blank: "著者" }, class: 'form-control'
            => f.select :tag_id, Tag.pluck(:name, :id) , { include_blank: "タグ" }, class: 'form-control'
            => f.search_field :body, class: 'form-control', placeholder: "記事内容"
            .input-group
              = f.search_field :title, class: 'form-control', placeholder: "タイトル"
              span.input-group-btn
                = f.submit '検索', class: %w[btn btn-default btn-flat]
        - if policy(Article).new?
          li
          .pull-right
            = link_to '新規作成', new_admin_article_path, class: %w[btn btn-primary]

  .box-body.table-responsive.no-padding
    table.table.table-hover
      thead
        tr
          th = Article.human_attribute_name(:id)
          th = Article.human_attribute_name(:title)
          th = Article.human_attribute_name(:category)
          th = Article.human_attribute_name(:tag)
          th = Article.human_attribute_name(:author)
          th = Article.human_attribute_name(:published_at)
      tbody
        - @articles.each do |article|
          tr
            td = article.id
            td
              div = article.title
              div
                - if policy(article).edit?
                  => link_to edit_admin_article_path(article.uuid), class: %w[btn btn-default btn-xs btn-flat]
                    i.fa.fa-edit
                    '
                    | 編集
                => link_to admin_article_preview_path(article.uuid), class: %w[btn btn-default btn-xs btn-flat], target: '_blank'
                  i.fa.fa-eye
                  '
                  | プレビュー
                - if policy(article).destroy?
                  => link_to admin_article_path(article.uuid), class: %w[btn btn-link btn-xs btn-flat], method: :delete, data: { confirm: "#{article.title}を削除してもよろしいですか？" } do
                    i.fa.fa-trash
                    '
                    | 削除
            td = article.category_name
            td
              - article.tags.each do |tag|
                span.label.label-info
                  = tag.name
                '
            td = article.author_name
            td
              div
                - if article.published?
                  span.label.label-success = article.state_i18n
                - else
                  span.label.label-warning = article.state_i18n
              div = article.published_at? ? l(article.published_at) : '-'
  .box-footer
    .pull-right
      = paginate(@articles)

app/views/admin/articles/new.html.slim
= content_for 'content-header' do
  | 記事の作成

- breadcrumb :new_admin_article

.box.box-primary
  .box-header
    h3.box-title 新規作成
  = simple_form_for [:admin, @article] do |f|
    .box-body
      = f.error_notification
      = f.input :title
      = f.input :slug
      = f.input :description
    .box-footer
      = f.button :submit, class: %w[btn btn-primary]