config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    get '/login_as/:user_id', to: 'development/sessions#login_as'
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  namespace :admin do
    namespace :login do
      resource :identifier, only: %i[show create]
      resource :password, only: %i[show create]
    end
    resource :logout, only: %i[destroy]
    resource :dashboard, only: %i[show]
    resources :users
    resources :invitations, param: :uuid, only: %i[index new create destroy] do
      resource :register, only: %i[show create]
    end
    resource :site, only: %i[edit update] do
      resources :attachments, controller: 'site/attachments', only: %i[destroy]
    end
    resources :categories, only: %i[index create edit update destroy]
    resources :tags, only: %i[index create edit update destroy]
    resources :authors, only: %i[index create edit update destroy]
    resources :articles, param: :uuid, only: %i[index new create edit update destroy] do
      resource :preview, controller: 'articles/previews', only: %i[show]
      resource :publish, controller: 'articles/publishes', only: %i[update]
      resources :article_blocks, controller: 'articles/article_blocks', only: %i[index show create edit update destroy] do
        patch :swap_level
      end
    end
  end

  get '/admin' => redirect('/admin/login/identifier')

  get '/tags/:tag_slug', as: :tag, to: 'articles#index'
  get '/authors/:author_slug', as: :author, to: 'articles#index'
  get '/:category_slug', as: :category, to: 'articles#index'
  get '/:category_slug/:article_slug', as: :article, to: 'articles#show'

  root 'articles#index'
end

app/models/author.rb
# == Schema Information
#
# Table name: taxonomies
#
#  id          :bigint           not null, primary key
#  type        :string(255)
#  name        :string(255)
#  slug        :string(255)
#  description :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_taxonomies_on_slug  (slug)
#  index_taxonomies_on_type  (type)
#

class Author < Taxonomy
  has_many :articles

  has_one_attached :avatar

  validates :avatar, attachment: { purge: true, content_type: %r{\Aimage/(png|jpeg)\Z}, maximum: 10_485_760 }
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
  layout 'admin'

  before_action :set_authors, only: %i[index]
  before_action :set_author, only: %i[edit update destroy]

  def index
    authorize(Author)

    @author = Author.new
  end

  def create
    authorize(Author)

    @author = Author.new(author_params)

    if @author.save
      redirect_to admin_authors_path
    else
      set_authors
      render :index
    end
  end

  def edit
    authorize(@author)
  end

  def update
    authorize(@author)

    if @author.update(author_params)
      redirect_to admin_authors_path
    else
      render :edit
    end
  end

  def destroy
    authorize(@author)

    @author.destroy

    redirect_to admin_authors_path
  end

  private

  def author_params
    params.require(:author).permit(:name, :slug, :description, :avatar)
  end

  def set_author
    @author = Author.find(params[:id])
  end

  def set_authors
    @authors = Author.all.order(:slug)
  end
end

app/views/admin/authors/_form.html.slim
= simple_form_for [:admin, author] do |f|
  .box-body
    = f.error_notification
    = f.input :name
    = f.input :slug
    = f.input :description
    = f.input :avatar, as: :file
    - if author.avatar.attached?
      = image_tag author.avatar_url(:icon)
  .box-footer
    = f.button :submit, class: %w[btn btn-primary]

app/views/admin/authors/edit.html.slim
= content_for 'content-header' do
  | 著者編集

- breadcrumb :edit_admin_author, @author

.box
  = render 'form', author: @author

app/views/admin/authors/index.html.slim
= content_for 'content-header' do
  | 著者

- breadcrumb :admin_authors

.row
  .col-md-9
    .box.box-primary
      .box-body.table-responsive.no-padding
        table.table.table-hover
          thead
            tr
              th = Author.human_attribute_name(:id)
              th
              th = Author.human_attribute_name(:name)
              th = Author.human_attribute_name(:slug)
              th = Author.human_attribute_name(:created_at)
              th
              th
          tbody
            - @authors.each do |author|
              tr
                td = author.id
                td = image_tag author.avatar_url(:icon), class: 'image-icon-xs'
                td = author.name
                td = author.slug
                td = l(author.created_at)
                td
                  = link_to '編集', edit_admin_author_path(author)
                td
                  = link_to admin_author_path(author), method: :delete, data: { confirm: "#{author.name}を削除してもよろしいですか？" } do
                    i.fa.fa-trash
                    '
                    | 削除

  .col-md-3
    .box
      .box-header
        h3.box-title 新規作成
      = render 'form', author: @author