config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    get '/login_as/:user_id', to: 'development/sessions#login_as'
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  namespace :admin do
    namespace :login do
      resource :identifier, only: %i[show create]
      resource :password, only: %i[show create]
    end
    resource :logout, only: %i[destroy]
    resource :dashboard, only: %i[show]
    resources :users
    resources :invitations, param: :uuid, only: %i[index new create destroy] do
      resource :register, only: %i[show create]
    end
    resource :site, only: %i[edit update] do
      resources :attachments, controller: 'site/attachments', only: %i[destroy]
    end
    resources :categories, only: %i[index create edit update destroy]
    resources :tags, only: %i[index create edit update destroy]
    resources :authors, only: %i[index create edit update destroy]
    resources :articles, param: :uuid, only: %i[index new create edit update destroy] do
      resource :preview, controller: 'articles/previews', only: %i[show]
      resource :publish, controller: 'articles/publishes', only: %i[update]
      resources :article_blocks, controller: 'articles/article_blocks', only: %i[index show create edit update destroy] do
        patch :swap_level
      end
    end
  end

  get '/admin' => redirect('/admin/login/identifier')

  get '/tags/:tag_slug', as: :tag, to: 'articles#index'
  get '/authors/:author_slug', as: :author, to: 'articles#index'
  get '/:category_slug', as: :category, to: 'articles#index'
  get '/:category_slug/:article_slug', as: :article, to: 'articles#show'

  root 'articles#index'
end

app/views/shared/_article.html.slim
.container.article-content
  h1.title = article.title

  section.published-at
    time
      = l(article.published_at? ? article.published_at.to_date : Time.current.to_date, format: '%Y年%-m月%-d日')

  - if article.eye_catch.attached?
    section.eye_catch class="text-#{article.eyecatch_align}"
      = image_tag article.eye_catch_url(:lg), class: 'img-fluid', width: article.eyecatch_width

  - if article.category.present?
    section.category
      h4 Category
      = link_to article.category.name, category_path(article.category.slug)

  - if article.tags.present?
    section.tags
      h4 Tags
      ul.list-inline
      - article.tags.each do |tag|
        li.list-inline-item = link_to tag.name, tag_path(tag.slug)

  article.article
    == article.body

  - if article.author.present?
    section.author.my-5
      .card
        .card-body
          .media
            = image_tag article.author.avatar_url(:media), class: 'mr-3', style: 'width: 64px; height: 64px;'
            .media-body
              h5.mt-0 = link_to article.author.name, author_path(article.author.slug)
              = article.author.description

  section.row.next-article.my-5
    .col-sm-6
      - if article.prev_article.present?
        .card
          .card-body
            h6.card-title.text-center 古い記事
            h6.card-title
              = link_to article.prev_article.title, article_path(article.prev_article.category_slug, article.prev_article.slug)
    .col-sm-6
      - if article.next_article.present?
        .card
          .card-body
            h6.card-title.text-center 新しい記事
            h6.card-title
              = link_to article.next_article.title, article_path(article.next_article.category_slug, article.next_article.slug)

app/views/shared/_article_card.html.slim
- cache article do
  .card
    - if article.eye_catch.attached?
      = link_to article_path(article.category_slug, article.slug) do
        = image_tag article.eye_catch_url(:thumb), class: 'card-img-top'

    .card-body
      p.card-link = link_to article.category_name, category_path(article.category_slug)
      h5.card-title
        = link_to article_path(article.category_slug, article.slug) do
          = article.title
      p.card-text
        small.text-muted = l(article.published_at || Time.current, format: '%Y年%-m月%-d日')

app/views/shared/_articles.html.slim
- if pagination?
  div.d-flex.justify-content-center
    = paginate articles, theme: 'twitter-bootstrap-4'

.card-columns
  - articles.each do |article|
    = render 'shared/article_card', article: article

- if pagination?
  div.d-flex.justify-content-center
    = paginate articles, theme: 'twitter-bootstrap-4'

app/views/shared/_categories.html.slim
h3.text-center.mb-5 カテゴリ
.d-flex.justify-content-between
  - categories.each do |category|
    = link_to category.name, category_path(category.slug), class: %w[btn btn-link btn-lg btn-outline-primary]

app/views/shared/_embed_twitter.html.slim
ruby:
  embed = local_assigns[:embed]
  width = local_assigns[:width] || 853
  height = local_assigns[:height] || 480
  
.embed-twitter
  blockquote.twitter-tweet 
    a href="#{embed.identifier}"
  script async="" charset='utf-8' src="https://platform.twitter.com/widgets.js"

app/views/shared/_embed_youtube.html.slim
ruby:
  embed = local_assigns[:embed]
  width = local_assigns[:width] || 853
  height = local_assigns[:height] || 480

.embed-youtube
  = content_tag 'iframe', nil, width: width, height: height, src: "https://www.youtube.com/embed/#{embed.split_id_from_youtube_url}", \
    frameborder: 0, gesture: 'media', allow: 'encrypted-media', allowfullscreen: true

app/views/shared/_media_image.html.slim
ruby:
  medium = local_assigns[:medium]

-if medium.image_url
  .media-image
    = image_tag medium.image_url(:lg)

app/views/shared/_new_arrival_articles.html.slim
h3.text-center.mb-5 新着記事
.card-deck
  - articles.each do |article|
    = render 'shared/article_card', article: article