config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    get '/login_as/:user_id', to: 'development/sessions#login_as'
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  namespace :admin do
    namespace :login do
      resource :identifier, only: %i[show create]
      resource :password, only: %i[show create]
    end
    resource :logout, only: %i[destroy]
    resource :dashboard, only: %i[show]
    resources :users
    resources :invitations, param: :uuid, only: %i[index new create destroy] do
      resource :register, only: %i[show create]
    end
    resource :site, only: %i[edit update] do
      resources :attachments, controller: 'site/attachments', only: %i[destroy]
    end
    resources :categories, only: %i[index create edit update destroy]
    resources :tags, only: %i[index create edit update destroy]
    resources :authors, only: %i[index create edit update destroy]
    resources :articles, param: :uuid, only: %i[index new create edit update destroy] do
      resource :preview, controller: 'articles/previews', only: %i[show]
      resource :publish, controller: 'articles/publishes', only: %i[update]
      resources :article_blocks, controller: 'articles/article_blocks', only: %i[index show create edit update destroy] do
        patch :swap_level
      end
    end
  end

  get '/admin' => redirect('/admin/login/identifier')

  get '/tags/:tag_slug', as: :tag, to: 'articles#index'
  get '/authors/:author_slug', as: :author, to: 'articles#index'
  get '/:category_slug', as: :category, to: 'articles#index'
  get '/:category_slug/:article_slug', as: :article, to: 'articles#show'

  root 'articles#index'
end

app/models/invitation.rb
# == Schema Information
#
# Table name: invitations
#
#  id         :bigint           not null, primary key
#  uuid       :string(255)      not null
#  name       :string(255)      not null
#  role       :integer          default("writer")
#  user_id    :bigint
#  expires_at :datetime         not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#
# Indexes
#
#  index_invitations_on_deleted_at  (deleted_at)
#  index_invitations_on_user_id     (user_id)
#  index_invitations_on_uuid        (uuid) UNIQUE
#

class Invitation < ApplicationRecord
  include UserName
  include Role

  belongs_to :user

  delegate :name, to: :user, prefix: true, allow_nil: true

  validate :valid_unique_username?

  before_create -> { self.uuid = SecureRandom.uuid }
  before_create -> { self.expires_at = 1.day.since }

  scope :validity, -> { where('expires_at > ?', Time.zone.now) }

  def valid_unique_username?
    if User.exists?(name: name)
      errors.add(:name, 'は登録されています')
      false
    else
      true
    end
  end

  def expired?
    expires_at <= Time.zone.now
  end
end

app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < ApplicationController
  layout 'admin'

  before_action :set_invitation, only: %i[show destroy]

  def index
    authorize(Invitation)

    @invitations = Invitation.order(:expires_at)
  end

  def new
    authorize(Invitation)

    @invitation = Invitation.new
  end

  def show; end

  def create
    authorize(Invitation)

    @invitation = Invitation.new(invitation_params)

    if @invitation.valid?
      @invitation.user = current_user
      @invitation.save!
    else
      render :new
    end
  end

  def destroy
    authorize(@invitation)

    @invitation.destroy!

    redirect_to admin_invitations_path
  end

  private

  def invitation_params
    params.require(:invitation).permit(:name, :role)
  end

  def set_invitation
    @invitation = Invitation.find_by!(uuid: params[:uuid])
  end
end

app/views/admin/invitations/create.html.slim
= content_for 'content-header' do
  | 招待状の作成

- breadcrumb :new_admin_invitation

.box.box-primary
  .box-header
    h3.box-title 招待状を作成しました

  .box-body
    dl.dl-horizontal
      dt = Invitation.human_attribute_name(:name)
      dd = @invitation.name

      dt = Invitation.human_attribute_name(:role)
      dd = @invitation.role_i18n

    p 以下のURLを招待する方に共有してください

    input.form-control[type="text" readonly value="#{admin_invitation_register_url(@invitation.uuid)}"]

  .box-footer
    = link_to '戻る', admin_invitations_path, class: %w[btn btn-link]

app/views/admin/invitations/index.html.slim
= content_for 'content-header' do
  | 招待

- breadcrumb :admin_invitations

.box.box-primary
  .box-header
    h3.box-title 招待一覧
    .pull-right.box-tools
      - if policy(Invitation).new?
        = link_to '新規作成', new_admin_invitation_path, class: %w[btn btn-primary btn-sm]
  .box-body.table-responsive.no-padding
    table.table.table-hover
      thead
        tr
          th = Invitation.human_attribute_name(:id)
          th = Invitation.human_attribute_name(:name)
          th = Invitation.human_attribute_name(:role)
          th = Invitation.human_attribute_name(:user_name)
          th = Invitation.human_attribute_name(:created_at)
          th = Invitation.human_attribute_name(:expires_at)
          th
          th
      tbody
        - @invitations.each do |invitation|
          tr
            td = invitation.id
            td = invitation.name
            td = invitation.role_i18n
            td = invitation.user_name
            td = l(invitation.created_at)
            td = l(invitation.expires_at)
            td
              - if policy(invitation).create?
                .modal.fade[id="invitation-url-#{invitation.id}"]
                  .modal-dialog
                    .modal-content
                      .modal-header
                        h4.modal-title ユーザー招待URL
                      .modal-body
                        input.form-control[type="text" readonly value="#{admin_invitation_register_url(invitation.uuid)}"]
                      .modal-footer
                        button.btn.btn-default[data-dismiss="modal"] 閉じる
                a[href="#" data-toggle="modal" data-target="#invitation-url-#{invitation.id}"] URL

            td
              - if policy(invitation).destroy?
                = link_to admin_invitation_path(invitation.uuid), method: :delete, data: { confirm: "#{invitation.name}の招待を削除してもよろしいですか？" } do
                  i.fa.fa-trash
                  '
                  | 削除

app/views/admin/invitations/new.html.slim
= content_for 'content-header' do
  | 招待状の作成

- breadcrumb :new_admin_invitation

.box.box-primary
  = simple_form_for [:admin, @invitation] do |f|
    .box-body
      = f.error_notification
      = f.input :name
      = f.input :role, collect: Invitation.roles_i18n.invert

    .box-footer
      = f.button :submit, class: %w[btn btn-primary]